services:
  - type: web
    name: roastme-api
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: FRONTEND_URL
        value: https://alexwoodhx.github.io
      # The following environment variables should be set in the Render dashboard
      # - key: MONGODB_URI
      #   sync: false
      # - key: OPENAI_API_KEY
      #   sync: false
      # - key: STRIPE_SECRET_KEY
      #   sync: false
      # - key: STRIPE_WEBHOOK_SECRET
      #   sync: false 