// Mock roasts for when OpenAI API is not available - with British humour style
const basicMockRoasts = [
  "NAME looks like they were assembled from spare parts found in a discount bin at Poundland. Their fashion sense screams 'I've given up on life' and their personality has all the depth of a puddle in the Sahara.",
  "If mediocrity had a poster child, it would be NAME. Their life achievements could fit on a Post-it note with room to spare, and their sex life is so non-existent that even their right hand has filed for divorce. They're about as exciting as a rainy bank holiday in Bognor Regis.",
  "NAME is living proof that evolution can go in reverse. Their IQ is lower than their shoe size, and their dating history reads like a cautionary tale they should show in sex ed classes at comprehensive schools across the UK.",
  "I've seen more charisma in a cardboard cutout of Prince Andrew than NAME has in their entire body. They're so boring in bed that their partners fake sleep instead of orgasms. Even the Queen's corgis would find them dull.",
  "NAME is what happens when you order a personality from Wish.com. They're so generic that facial recognition software categorises them as 'background extra' and dating apps automatically swipe left. They're the human equivalent of a Greggs sausage roll that's been left out overnight.",
  "NAME has the charm of a wet sock and the sex appeal of an HMRC tax audit. Their personality is so bland it makes unseasoned tofu seem spicy by comparison, and their bedroom skills make celibacy look appealing. They're about as interesting as the shipping forecast at 3 AM.",
  "NAME is so irrelevant that even their MI5 agent stopped watching them out of boredom. Their existence is the human equivalent of beige wallpaper, and their dirty talk sounds like a corporate email from Tesco customer service.",
  "NAME's face looks like it was designed by someone who heard about human features but never actually saw them. Their personality has all the complexity of a stick figure drawing, and their idea of foreplay is asking 'fancy a cuppa?' before bed.",
  "NAME is what happens when you hit 'randomise' on the character creation screen and then select 'no personality' as a trait. Their dating profile is so sad that dating apps created a special algorithm just to hide it from potential matches out of mercy. They're the human equivalent of a soggy digestive biscuit.",
  "If disappointment needed a mascot, NAME would be on the shortlist. They have the ambition of a sloth and the sexual prowess of a virgin at a family reunion in Slough. Even their own reflection looks bored when they check themselves out in the mirror at Primark."
];

const premiumMockRoasts = [
  "NAME is what you'd get if failure and disappointment had a baby and then dropped it on its head repeatedly at a Wetherspoons. Their face looks like it was designed by an AI that was fed nothing but images of potatoes, and their personality has all the depth and complexity of a puddle in a car park. Their sex life is so pathetic that even their browser history is embarrassed for them, and their bedroom skills make a dead fish look passionate.",
  "I've seen more talent in a Blackpool public toilet than NAME has in their entire body. Their career aspirations have the trajectory of a brick thrown into a well, and their dating history reads like a cautionary tale they should tell in schools across the Midlands. NAME's idea of intellectual conversation is debating which flavour of Walkers crisps is superior while living in their parents' semi-detached in Swindon, and their idea of foreplay is asking 'did you shower today, love?'",
  "NAME is so forgettable that their own diary entries start with 'Dear whoever this belongs to.' Their face has all the distinguishing features of unbuttered toast from Tesco Value range, and their personality makes watching paint dry seem like an extreme sport. NAME's greatest achievement to date is managing to dress themselves in the morning without adult supervision, though the results suggest they might need it. Their sex appeal is so non-existent that even their own hand falls asleep during masturbation.",
  "NAME is living proof that God sometimes just hits the 'randomise' button and walks away. Their face looks like it was assembled from mismatched parts found in a discount bin at Argos, and their fashion sense screams 'I was dressed by feral badgers.' NAME's attempts at humour are so painful that they've been classified as a form of psychological torture by the Geneva Convention. Their dating profile has been used by scientists at Oxford University to study the concept of absolute zero in terms of sex appeal.",
  "NAME has the charisma of a damp tea towel and the sex appeal of a root canal at an NHS dentist. Their idea of a personality is repeating quotes from BBC sitcoms they don't understand, and their laugh sounds like a donkey being strangled by a kazoo. NAME's dating profile is so sad that dating apps created a special algorithm just to hide it from potential matches out of mercy. Their bedroom skills are so bad that their ex filed for emotional damages after their first night together at a Premier Inn.",
  "If mediocrity had a poster child, it would reject NAME for not meeting the minimum standards. Their face has all the appeal of a week-old sandwich found under a couch in a Travelodge, and their personality could be outshined by a particularly dull rock from the Lake District. NAME's parents still introduce them as 'our other child' and keep their photos in the back of the family album. Their sex life is so non-existent that cobwebs have formed in places that should never have cobwebs.",
  "NAME is what happens when the universe wants to make a joke but runs out of good material. Their face looks like it was designed by someone who heard about human features but never actually saw them. NAME's career aspirations have all the ambition of a sloth on tranquilisers, and their love life is so barren it qualifies as a protected desert ecosystem under the National Trust. Their idea of dirty talk would make a corporate HR training video from Marks & Spencer seem erotic by comparison.",
  "NAME is so basic that pH scales use them as a reference point. Their personality is a bland smoothie of borrowed opinions and regurgitated TikTok trends. NAME's idea of adventure is trying a different flavour of Nando's sauce, and their most passionate relationship is with their phone charger. Their bedroom skills are so disappointing that their ex partners have formed a support group that meets weekly at the local Wetherspoons to recover from the trauma of faking interest.",
  "NAME looks like they were created when God was on a tight deadline and just said 'sod it, ship it.' Their face has all the symmetry of a Picasso painting during an earthquake, and their body appears to be actively fighting against any attempt at fitness. NAME's personality is so non-existent that ghost hunters have more luck finding spirits at Hampton Court Palace than anyone has finding a single original thought in their head. Their sexual prowess is so lacking that they once made a blow-up doll deflate itself out of sheer boredom.",
  "NAME is what you'd get if you asked AI to generate a human with no redeeming qualities and then fed it exclusively British tabloids. Their face is a masterclass in asymmetry, and their body looks like it's been storing food for several consecutive apocalypses at a Tesco Extra. NAME's idea of intellectual discourse is arguing about football teams down at the local pub, and their dating history reads like a series of hostage situations where Stockholm syndrome was the best outcome. Their bedroom performance has been described by ex-partners as 'a disappointing sneeze followed by immediate apologies and a cup of tea.'"
];

// Function to generate a mock roast
const generateMockRoast = (name, isPremium = false) => {
  const roasts = isPremium ? premiumMockRoasts : basicMockRoasts;
  const randomIndex = Math.floor(Math.random() * roasts.length);
  return roasts[randomIndex].replace(/NAME/g, name);
};

module.exports = {
  generateMockRoast
}; 