// Mock roasts for when OpenAI API is not available - with adult-oriented content and UK spelling
const basicMockRoasts = [
  "NAME looks like they were assembled from spare parts found in a discount bin. Their fashion sense screams 'I've given up on life' and their personality has all the depth of a puddle in the Sahara.",
  "If mediocrity had a poster child, it would be NAME. Their life achievements could fit on a Post-it note with room to spare, and their sex life is so non-existent that even their right hand has filed for divorce.",
  "NAME is living proof that evolution can go in reverse. Their IQ is lower than their shoe size, and their dating history reads like a cautionary tale they should show in sex ed classes.",
  "I've seen more charisma in a cardboard cutout than NAME has in their entire body. They're so boring in bed that their partners fake sleep instead of orgasms.",
  "NAME is what happens when you order a personality from Wish.com. They're so generic that facial recognition software categorises them as 'background extra' and people cross the street when they see them coming.",
  "NAME has the charm of a wet sock and the sex appeal of a tax audit. Their personality is so bland it makes unseasoned tofu seem spicy by comparison, and their bedroom skills make celibacy look appealing.",
  "NAME is so irrelevant that even their internet search history is boring. Their existence is the human equivalent of beige wallpaper, and their dirty talk sounds like a corporate email.",
  "NAME's face looks like it was designed by someone who heard about human features but never actually saw them. Their personality has all the complexity of a stick figure drawing, and their idea of foreplay is asking if you're still awake.",
  "NAME is what happens when you hit 'randomise' on the character creation screen and then select 'no personality' as a trait. Their social media presence is so dull that algorithms actively hide their content to prevent mass boredom.",
  "If disappointment needed a mascot, NAME would be on the shortlist. They have the ambition of a sloth and the sexual prowess of a virgin at a family reunion. Even their own reflection looks bored when they check themselves out."
];

const premiumMockRoasts = [
  "NAME is what you'd get if failure and disappointment had a baby and then dropped it on its head repeatedly. Their face looks like it was designed by an AI that was fed nothing but images of potatoes, and their personality has all the depth and complexity of a puddle in a car park. Their sex life is so pathetic that even their browser history is embarrassed for them, and their bedroom skills make a dead fish look passionate.",
  "I've seen more talent in a public toilet than NAME has in their entire body. Their career aspirations have the trajectory of a brick thrown into a well, and their romantic history reads like a cautionary tale they should tell in schools. NAME's idea of intellectual conversation is debating which flavour of crisps is superior while living in their parents' house at 35, and their idea of foreplay is asking 'did you shower today?'",
  "NAME is so forgettable that their own diary entries start with 'Dear whoever this belongs to.' Their face has all the distinguishing features of unbuttered toast, and their personality makes watching paint dry seem like an extreme sport. NAME's greatest achievement to date is managing to dress themselves in the morning without adult supervision, though the results suggest they might need it. Their sex appeal is so non-existent that even their own hand falls asleep during masturbation.",
  "NAME is living proof that God sometimes just hits the 'randomise' button and walks away. Their face looks like it was assembled from mismatched parts found in a discount bin, and their fashion sense screams 'I was dressed by feral animals.' NAME's attempts at humour are so painful that they've been classified as a form of psychological torture by the Geneva Convention. Their social interactions have been studied by scientists as a perfect example of how not to communicate with other humans.",
  "NAME has the charisma of a damp tea towel and the sex appeal of a root canal. Their idea of a personality is repeating quotes from sitcoms they don't understand, and their laugh sounds like a donkey being strangled by a kazoo. Their attempts at flirting are so awkward that potential partners have reported feeling secondhand embarrassment strong enough to require therapy.",
  "If mediocrity had a poster child, it would reject NAME for not meeting the minimum standards. Their face has all the appeal of a week-old sandwich found under a couch, and their personality could be outshined by a particularly dull rock. NAME's parents still introduce them as 'our other child' and keep their photos in the back of the family album. Their sex life is so non-existent that cobwebs have formed in places that should never have cobwebs.",
  "NAME is what happens when the universe wants to make a joke but runs out of good material. Their face looks like it was designed by someone who heard about human features but never actually saw them. NAME's career aspirations have all the ambition of a sloth on tranquilisers, and their love life is so barren it qualifies as a protected desert ecosystem. Their idea of dirty talk would make a corporate HR training video seem erotic by comparison.",
  "NAME is so basic that pH scales use them as a reference point. Their personality is a bland smoothie of borrowed opinions and regurgitated social media trends. NAME's idea of adventure is trying a different flavour of sauce, and their most passionate relationship is with their phone charger. Their romantic history consists entirely of people who were too polite to say no but mysteriously developed sudden family emergencies within an hour.",
  "NAME looks like they were created when God was on a tight deadline and just said 'sod it, ship it.' Their face has all the symmetry of a Picasso painting during an earthquake, and their body appears to be actively fighting against any attempt at fitness. NAME's personality is so non-existent that ghost hunters have more luck finding spirits than anyone has finding a single original thought in their head. Their sexual prowess is so lacking that they once made a blow-up doll deflate itself out of sheer boredom.",
  "NAME is what you'd get if you asked AI to generate a human with no redeeming qualities. Their face is a masterclass in asymmetry, and their body looks like it's been storing food for several consecutive apocalypses. NAME's idea of intellectual discourse is arguing about fast food chains, and their romantic history reads like a series of hostage situations where Stockholm syndrome was the best outcome. Their bedroom performance has been described by ex-partners as 'a disappointing sneeze followed by immediate apologies.'"
];

// Function to generate a mock roast
const generateMockRoast = (name, isPremium = false) => {
  const roasts = isPremium ? premiumMockRoasts : basicMockRoasts;
  const randomIndex = Math.floor(Math.random() * roasts.length);
  return roasts[randomIndex].replace(/NAME/g, name);
};

module.exports = {
  generateMockRoast
}; 