name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: 'frontend/package-lock.json'
      
      - name: Install dependencies
        run: cd frontend && npm ci
      
      - name: Build
        run: cd frontend && npm run build
      
      - name: Prepare for deployment
        run: |
          # Create .nojekyll file
          touch frontend/dist/.nojekyll
          
          # Create a clean build directory with only the necessary files
          mkdir -p /tmp/gh-pages-deploy
          cp -r frontend/dist/* /tmp/gh-pages-deploy/
          cp frontend/dist/.nojekyll /tmp/gh-pages-deploy/
          
          # Debug info
          echo "Contents of deployment directory:"
          ls -la /tmp/gh-pages-deploy
          echo "Total size:"
          du -sh /tmp/gh-pages-deploy
      
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: /tmp/gh-pages-deploy
          branch: gh-pages
          clean: true
          single-commit: true 